---
- name: Put take_phote.sh
  ansible.builtin.copy:
    src: take_photo.sh
    dest: /usr/local/src/
    force: true
    mode: "755"
  become: true

- name: Put take_phote service files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/systemd/system
    force: true
    mode: "755"
  become: true
  loop:
    - take_photo.service
    - take_photo.timer

- name: Enable service files
  ansible.builtin.systemd:
    name: take_photo.timer
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
