---
- name: Clone maru_web
  ansible.builtin.git:
    repo: https://github.com/ganpori/maru_web.git
    dest: ~/maru_web
    version: main

# pyenvによるpythonのバージョンとかpoetryのインストール済みかとかの依存関係があるけどとりあえず気にしない。
# 上記のインストールはmerge_movieロールの中で実施してる。
# cmdの返り値に対する挙動決めろっていうwarning出てるけど気にしない。
# https://ansible.readthedocs.io/projects/lint/rules/no-changed-when/#correct-code
- name: Create .venv by poetry
  ansible.builtin.command:
    cmd: "{{ item }}"
    chdir: ~/maru_web # ワーキン グディレクトリ変えなければいけないの注意
  loop:
    - ~/.local/bin/poetry env use ~/.pyenv/versions/3.11.4/bin/python3.11
    - ~/.local/bin/poetry install
  # BUG:初回はkeyringのgui プロンプトが出てきてうまく進まなくなる。vnc使って手動でプロンプトすすめるようにする
  # このあとwebをアプリ動かすためにdbの初期化とtorchのモデルを配置しなければならない。それは自動化しない。やり方はmaru_web/README.mdを参照。

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
  become: true

# nginxが削除することを推奨している。
# /etc/nginx/sites-enabledと/etc/nginx/sites-available自体がdebian特有の使い方でよくないらしい
- name: Delete nginx default config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true

- name: Put maru_web.conf
  ansible.builtin.copy:
    src: maru_web.conf
    dest: /etc/nginx/conf.d
    force: true
    mode: "644"
  become: true

- name: Enable maru_web nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
