---
# pyenvのインストール方法の公式ページ
- name: Add pyenv path to .bashrc # pathの追加の仕方はpyenvのバージョンごとに少し変わっていくので注意。この書き方はすでに古いがとりあえず動く。
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: "{{ item }}"
    state: present
  loop:
    - export PYENV_ROOT="$HOME/.pyenv"
    - export PATH="$PYENV_ROOT/bin:$PATH"

- name: Add pyenv path to .profile # ansibleからpyenvへのpathがなかったのでとりあえず.profileにも書いておく。どこに書くべきかよくわからず。
  ansible.builtin.lineinfile:
    dest: ~/.profile
    line: "{{ item }}"
    state: present
  loop:
    - export PYENV_ROOT="$HOME/.pyenv"
    - export PATH="$PYENV_ROOT/bin:$PATH"

- name: Install gcc and make for build python
  ansible.builtin.apt: # pyenvでpython3.9をbuildするためにコンパイラ導入
    name: "{{ item }}"
    state: present
  loop:
    - gcc
    - make
  become: true

  # https://github.com/pyenv/pyenv/wiki#suggested-build-environment
- name: Install libs suggested by pyenv
  ansible.builtin.apt: # pyenvでpython3.9をbuildするためにコンパイラ導入
    name: "{{ item }}"
    state: present
  loop:
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - libxml2-dev
    - libxmlsec1-dev
    - libffi-dev
    - liblzma-dev
  become: true

- name: Check pyenv is installed
  ansible.builtin.stat:
    path: ~/.pyenv/bin/pyenv
  register: result_pyenv

- name: Fetch pyenv repository(ネットつながってないととってこれない。install済みなら実行しない)
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/.pyenv
    version: v2.3.20
  when: not result_pyenv.stat.exists # ネット接続していないスタンドアロンPCでもアップデート可能にするためこうした。
