---
- name: Install pyenv
  ansible.builtin.import_tasks: install_pyenv.yaml

- name: Install poetry
  ansible.builtin.import_tasks: install_poetry.yaml

- name: Clone merge_movie
  ansible.builtin.git:
    repo: https://github.com/ganpori/merge_movie.git
    dest: ~/merge_movie
    version: main

- name: Install python3.11 for merge_movie by pyenv
  ansible.builtin.command:
    cmd: "~/.pyenv/bin/pyenv install 3.11.4  --skip-existing" # 環境変数読み込むのが大変なので直接pyenvのパス指定する

- name: create .venv by poetry(ネットつながってないと失敗する)
  ansible.builtin.command:
    cmd: "{{ item }}"
    chdir: ~/merge_movie
  loop:
    - ~/.local/bin/poetry env use ~/.pyenv/versions/3.11.4/bin/python3.11
    - ~/.local/bin/poetry install # BIUG:初回はkeyringのgui プロンプトが出てきてうまく進まなくなる。vnc使って手動でプロンプトすすめるようにする

- name: Install ffmpeg
  ansible.builtin.apt:
    name: ffmpeg
  become: true
